/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AppUserRole = IDL.Variant({
  'admin' : IDL.Null,
  'fieldManager' : IDL.Null,
  'landOwner' : IDL.Null,
  'expert' : IDL.Null,
  'worker' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CropType = IDL.Variant({
  'maize' : IDL.Null,
  'onion' : IDL.Null,
  'sugarCane' : IDL.Null,
  'banana' : IDL.Null,
  'turmeric' : IDL.Null,
  'tomato' : IDL.Null,
  'chilli' : IDL.Null,
  'paddy' : IDL.Null,
  'groundnut' : IDL.Null,
  'cotton' : IDL.Null,
});
export const FieldManagerProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'fieldManager' : IDL.Principal,
  'assignedTo' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'deadline' : Time,
  'cropType' : CropType,
  'location' : IDL.Text,
});
export const WorkerProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const ExpertProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const FieldPhoto = IDL.Record({
  'url' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'uploadedBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignAppUserRole' : IDL.Func([IDL.Principal, AppUserRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTaskToMultipleWorkers' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Principal)],
      [],
      [],
    ),
  'assignTaskToWorker' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Vec(IDL.Principal),
        CropType,
        IDL.Principal,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getAllFieldManagerProfiles' : IDL.Func(
      [],
      [IDL.Vec(FieldManagerProfile)],
      ['query'],
    ),
  'getAllFieldManagers' : IDL.Func(
      [],
      [IDL.Vec(FieldManagerProfile)],
      ['query'],
    ),
  'getAllTasksByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getAllTasksForFieldManager' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getAllTasksForWorker' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getAppUserRole' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AppUserRole)],
      ['query'],
    ),
  'getCallerExpertProfile' : IDL.Func([], [IDL.Opt(ExpertProfile)], ['query']),
  'getCallerFieldManagerProfile' : IDL.Func(
      [],
      [IDL.Opt(FieldManagerProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
  'getTaskByName' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskComplete' : IDL.Func([IDL.Text], [], []),
  'saveCallerExpertProfile' : IDL.Func([ExpertProfile], [], []),
  'saveCallerFieldManagerProfile' : IDL.Func([FieldManagerProfile], [], []),
  'saveCallerWorkerProfile' : IDL.Func([WorkerProfile], [], []),
  'uploadFieldPhoto' : IDL.Func([FieldPhoto], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AppUserRole = IDL.Variant({
    'admin' : IDL.Null,
    'fieldManager' : IDL.Null,
    'landOwner' : IDL.Null,
    'expert' : IDL.Null,
    'worker' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CropType = IDL.Variant({
    'maize' : IDL.Null,
    'onion' : IDL.Null,
    'sugarCane' : IDL.Null,
    'banana' : IDL.Null,
    'turmeric' : IDL.Null,
    'tomato' : IDL.Null,
    'chilli' : IDL.Null,
    'paddy' : IDL.Null,
    'groundnut' : IDL.Null,
    'cotton' : IDL.Null,
  });
  const FieldManagerProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'fieldManager' : IDL.Principal,
    'assignedTo' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'deadline' : Time,
    'cropType' : CropType,
    'location' : IDL.Text,
  });
  const WorkerProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ExpertProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const FieldPhoto = IDL.Record({
    'url' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'uploadedBy' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignAppUserRole' : IDL.Func([IDL.Principal, AppUserRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTaskToMultipleWorkers' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
    'assignTaskToWorker' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Vec(IDL.Principal),
          CropType,
          IDL.Principal,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getAllFieldManagerProfiles' : IDL.Func(
        [],
        [IDL.Vec(FieldManagerProfile)],
        ['query'],
      ),
    'getAllFieldManagers' : IDL.Func(
        [],
        [IDL.Vec(FieldManagerProfile)],
        ['query'],
      ),
    'getAllTasksByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getAllTasksForFieldManager' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getAllTasksForWorker' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getAppUserRole' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AppUserRole)],
        ['query'],
      ),
    'getCallerExpertProfile' : IDL.Func(
        [],
        [IDL.Opt(ExpertProfile)],
        ['query'],
      ),
    'getCallerFieldManagerProfile' : IDL.Func(
        [],
        [IDL.Opt(FieldManagerProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWorkerProfile' : IDL.Func(
        [],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'getTaskByName' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskComplete' : IDL.Func([IDL.Text], [], []),
    'saveCallerExpertProfile' : IDL.Func([ExpertProfile], [], []),
    'saveCallerFieldManagerProfile' : IDL.Func([FieldManagerProfile], [], []),
    'saveCallerWorkerProfile' : IDL.Func([WorkerProfile], [], []),
    'uploadFieldPhoto' : IDL.Func([FieldPhoto], [], []),
  });
};

export const init = ({ IDL }) => { return []; };