/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'admin' : null } |
  { 'fieldManager' : null } |
  { 'landOwner' : null } |
  { 'expert' : null } |
  { 'worker' : null };
export type CropType = { 'maize' : null } |
  { 'onion' : null } |
  { 'sugarCane' : null } |
  { 'banana' : null } |
  { 'turmeric' : null } |
  { 'tomato' : null } |
  { 'chilli' : null } |
  { 'paddy' : null } |
  { 'groundnut' : null } |
  { 'cotton' : null };
export interface ExpertProfile { 'name' : string, 'role' : string }
export interface FieldManagerProfile { 'name' : string, 'role' : string }
export interface FieldPhoto {
  'url' : string,
  'description' : [] | [string],
  'timestamp' : Time,
  'uploadedBy' : Principal,
}
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'fieldManager' : Principal,
  'assignedTo' : Array<Principal>,
  'name' : string,
  'deadline' : Time,
  'cropType' : CropType,
  'location' : string,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkerProfile { 'name' : string, 'role' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignAppUserRole' : ActorMethod<[Principal, AppUserRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTaskToMultipleWorkers' : ActorMethod<
    [string, Array<Principal>],
    undefined
  >,
  'assignTaskToWorker' : ActorMethod<[string, Principal], undefined>,
  'createTask' : ActorMethod<
    [string, Time, Array<Principal>, CropType, Principal, string],
    undefined
  >,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getAllFieldManagerProfiles' : ActorMethod<[], Array<FieldManagerProfile>>,
  'getAllFieldManagers' : ActorMethod<[], Array<FieldManagerProfile>>,
  'getAllTasksByLocation' : ActorMethod<[string], Array<Task>>,
  'getAllTasksForFieldManager' : ActorMethod<[Principal], Array<Task>>,
  'getAllTasksForWorker' : ActorMethod<[Principal], Array<Task>>,
  'getAllWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'getAppUserRole' : ActorMethod<[Principal], [] | [AppUserRole]>,
  'getCallerExpertProfile' : ActorMethod<[], [] | [ExpertProfile]>,
  'getCallerFieldManagerProfile' : ActorMethod<[], [] | [FieldManagerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWorkerProfile' : ActorMethod<[], [] | [WorkerProfile]>,
  'getTaskByName' : ActorMethod<[string], [] | [Task]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskComplete' : ActorMethod<[string], undefined>,
  'saveCallerExpertProfile' : ActorMethod<[ExpertProfile], undefined>,
  'saveCallerFieldManagerProfile' : ActorMethod<
    [FieldManagerProfile],
    undefined
  >,
  'saveCallerWorkerProfile' : ActorMethod<[WorkerProfile], undefined>,
  'uploadFieldPhoto' : ActorMethod<[FieldPhoto], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];